#ifndef __TRESC3TYPEDEF_H__
#define __TRESC3TYPEDEF_H__


#define CMD_STATE_LINEAR 0
#define CMD_STATE_ANGULAR 1
#define CMD_STATE_IMU 2

#define CMD_TARGET_ODOM 3

#define MESSAGE_IMU
#define MESSAGE_IMU_X_INDEX 0
#define MESSAGE_IMU_Y_INDEX 4
#define MESSAGE_IMU_Z_INDEX 8

#define MESSAGE_VEL
#define MESSAGE_VEL_X_INDEX 0
#define MESSAGE_VEL_Y_INDEX 4 
#define MESSAGe_VEL_Z_INDEX 8




#endif // __TRESC3TYPEDEF_H__